### ISSUE TITLE
Failure when verifying a bug with status === "NEW"

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/bugmon#27]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/worker/bugmon-tc/bugmon_tc/report/cli.py", line 85, in main
    report(args.api_key, args.api_root, args.artifact, args.dry_run)
  File "/home/worker/bugmon-tc/bugmon_tc/report/cli.py", line 49, in report
    bugsy.request(f"bug/{bug_number}", "PUT", json=diff)
  File "/home/worker/.cache/pypoetry/virtualenvs/bugmon-tc-SPUUklYP-py3.8/lib/python3.8/site-packages/bugsy/bugsy.py", line 200, in request
    return self._handle_errors(self.session.request(method, url, **kwargs))
  File "/home/worker/.cache/pypoetry/virtualenvs/bugmon-tc-SPUUklYP-py3.8/lib/python3.8/site-packages/bugsy/bugsy.py", line 214, in _handle_errors
    raise BugsyException(result["message"], result.get("code"))
bugsy.errors.BugsyException: Message: You are not allowed to change the bug status from NEW to VERIFIED. Code: 123
```

**Comment by pyoor** [comment]
I ran into this issue again and realized that the best approach is to combine the `confirm` and `verify` commands into a single command as only one of the two can be performed depending on the bug state.
